### ISSUE TITLE
Ignore `Carthage/Checkouts/DIKit`

### ISSUE THREAD

**Issue by takasek** [ishkawa/DIKit#35]
When separating sources to some frameworks, there are multiple directories on project root.
But if we use dikitgen for the project root, it recognizes `Carthage/Checkouts/DIKit`...

I find several ways to solve this issue,

- static code to ignore `Carthage` directory.
- white listing by letting dikitgen accept multiple arguments.
- black listing
    - by command parameter which tells ignored directories
    - by introducing something such as `.digenkitignore`

The last one seems smart for me.  Any idea?

**Comment by ishkawa** [comment]
Hi, @takasek.
Thank you for reporting this issue.

Indeed, it would be great if dikitgen has black list to exclude directories from code generation source. Command parameter like `--exclude DIR` sounds good to me. If you're going to work on the feature, I'll be happy to review it. Otherwise, I'll implement the feature.

At this moment, I guess that you can work around this issue by running `dikitgen` for each frameworks separately.

**Comment by takasek** [comment]
Thank you for responding.
Okay, I'm going to try implementation with `--exclude DIR`.
